### ISSUE TITLE
Is there anyway to debug appsync resolvers locally?

### ISSUE THREAD

**Issue by simon998yang** [sid88in/serverless-appsync-plugin#122]

**Comment by austin43** [comment]
https://github.com/sid88in/serverless-appsync-plugin/issues/112

Looks like there's an effort to make that possible here.

**Comment by lolcoolkat** [comment]
I've been using Jest + test data to test my appsync resolvers lately. Also I primarily use DynamoDB so the https://github.com/99xt/serverless-dynamodb-local plugin works great for my needs.

**Comment by Knowledge91** [comment]
Any news on this one?

**Comment by bboure** [comment]
More than testing the api in local, what I am a bit more interested in right now is how to **write unit tests**.
If your unit tests are well covered, your API _should_ be fine once deployed.
Then if you really want to test it, you can actually deploy it on a dev stack on AWS and use it locally. This will actually give you results much more closer to the "Production reality".

I primarily use Lambda, so that makes it easy to test with Jest.
I keep my lambdas as skinny as possible and instead delegate all the work to my framework (the lambda resolvers just call my framework with the _event_ and returns the result).
Then, I am actually testing my framework with Jest.

Recently, I have been doing some thinking on how to unit test DynamoDb resolvers but I have not come to a solution yet. 

The tricky part here is to have a Velocity template interpreter, that then executes the request to dynamodb-local and passes the result to the response template which also should be interpreted and return a result.

As pointer out earlier, there is this repo
https://github.com/ConduitVC/appsync-serverless-emulator-example
I haven't looked at it into details yet but there is definitely some good clues there.

Actually I am still considering if using DynamoDb or not.
Most of the time, you will always want to do some extra work in the resolver like data validation and normalization for example. AFAIK, this is only possible through code (I use [Joi](https://github.com/hapijs/joi)), thus it forces me to use Lambdas anyways.

**Comment by fuji8bit** [comment]
Local Mocking and Testing of AppSync has been added to the Amplify Toolchain:

https://aws.amazon.com/blogs/mobile/amplify-framework-local-mocking/

The blog post enumerates the features and limitations.

**Comment by bboure** [comment]
Thank you @fuji8bit for pointing that out.

Mocking tools have indeed been deprecated and included into amplify.
Since it was not useable anymore with this plugin, I made a new Serverless plugin that solves this issue.

Please check https://www.npmjs.com/package/serverless-appsync-simulator
and https://github.com/bboure/serverless-appsync-simulator

**Comment by neerajg5** [comment]
@bboure the given links ( https://www.npmjs.com/package/serverless-appsync-simulator) suggest that how can appsync be simulated locally. However, just curious to know if there is any plan ( as mentioned in your post above) or work done around support for writing test cases using jest for dynamodb resolvers.

**Comment by bboure** [comment]
@neerajg5 Well that is a very old post of mine 😄 
I have not done any more research on this. Really, I don't think there is an easy way to test dynamodb resolvers (or even HTTP resolvers).
The best approach is probably to test it locally with the simulator. 
Later, test it again in a real deployed environment (simulator can be buggy too!!).
