### ISSUE TITLE
Error: An error occurred: GraphQlApiKeyDefault - API key not found

### ISSUE THREAD

**Issue by anupam-newgen** [sid88in/serverless-appsync-plugin#503]
Hi,

While running the "serverless deploy", getting below error:

ServerlessError: An error occurred: GraphQlApiKeyDefault - API key not found: da2-XXXXXXXXXXXXXXXXXXXX (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: XXXXXX-XXXXXX-XXXXXX-XXXXXX; Proxy: null).

I have noticed the API Key that existed in AppSync AWS under settings configuration is deleted (after expiration). 
I created a new API Key and still getting the same error. 

We are running : "serverless-appsync-plugin": "^1.4.0"

Is there anyway I can resolve this error?

**Comment by bboure** [comment]
When was your last deployment? 

API keys are deleted by AppSync when expired after 2 or 3 months (don't remember exactly).

This is a CloudFormation error and tbh, I am not sure how to resolve this.

Since your Key was deleted anyways, try the following:
- rename or add an API key with a different name than `Default` 

```yaml
    apiKeys:
      - name: MyKey
```

Then try deploying again. 

This will force removing the `GraphQlApiKeyDefault` resource from the CloudFormation template and create a new one (`GraphQlApiKeyMyKey `)

It should trick CloudFormation into not trying to update the key that was deleted.

**Comment by bboure** [comment]
@anupam-newgen did you solve your problem?

**Comment by anupam-newgen** [comment]
> @anupam-newgen did you solve your problem?

Sorry for the delayed response, 
No we were not able to resolve the problem by adding the apikeys solution suggested above.
But we were able to resolve the problem by completly removing the appsync from the account and adding it back again.
