### ISSUE TITLE
Changes detection

### ISSUE THREAD

**Issue by skymasseronir** [sid88in/serverless-appsync-plugin#539]
Hello guys,
I could not find a similar issue but feel free to let me know!

Is it expected that with this plugin the entire AppSync stack will be redeployed every time? (the validity of the api-keys is renewed at each deploy)

What I'd like to expect: 
`No changes to deploy. Deployment skipped.`

What I'm getting every time: a full redeploy.

Thanks in advance

**Comment by bboure** [comment]
It is indeed possible that a full re-deploy is performed each time if you are using an API key.
This is likely due to the renewal of the API key as you mentioned. 
This is the expected behaviour: (to force a key renewal without changing anything else)

However, CloudFormation should not change anything other than the API key. 

You you expect the deployment to be skipped, the only way I see is to use a fixed expiry for the api key (`expiresAt`).
You'd then have to manage the renewal date yourself.

**Comment by skymasseronir** [comment]
Thank you @bboure!
As you said `expiresAfter` was causing CF template changing every time!
