### ISSUE TITLE
Integrate custom IAM authentication 

### ISSUE THREAD

**Issue by sid88in** [sid88in/serverless-appsync-plugin#70]

**Comment by sid88in** [comment]
Plugin should be able to create IAM authentications for GraphQL endpoint. Right now only API Key and Cognito are supported.

**Comment by honkskillet** [comment]
I might take a stab at this issue this week because my App needs IAM auth so that I can have both authenticated and unauthenticated users have access to my appsync API (which you can't do with the cognito auth.  
I just figured out how to hard code my specific use case this via the web console (see https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/11#issuecomment-383740669)
Any pain points I should be aware of.

**Comment by sid88in** [comment]
perfect thanks

**Comment by honkskillet** [comment]
Hey, so, good new.  IAM is already supported as is.  No changes needed.  All you have to do is change the authenticat entry in your serverless.yml to

`authenticationType: AWS_IAM`

That will change the setting at **AWS AppSync > APIs > your_api > Setting > Authorization type**  to _AWS Identity and Access Management (IAM)_.  Unlike the API key or Cognito methods, there are no other fields to set.

So then the 2nd part of this equation is that you need to create an IAM Role.  The most common thing to do I'm thinking would be to assign an IAM role to a cognito user pool.  (Why do this instead of just using the Cognito Auth type?  Doing it this way provides more flexibility, for example allowing unauthenticated access to you API.)  But those roles and policies really belong to the cognito user pool and not appSync.  They should be provisioned by whatever provisioned the cognito user pool in the first place, right?  So if this plugin is expanded to  include creating cognito user pools, as suggested in issue #71, then it would make sense that the IAM role be created at the same time.

For now, if you'd still want to have serverless, you can add the IAM role to your resources in the serverless.yml.  For example,

```
service: your-service-name
frameworkVersion: ">=1.21.0 <2.0.0"
provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-appsync-plugin


custom:
  accountId: # replace this with your accountId
  cognitoIdentityPoolId: # find at Cognito > Federated Identities > your identity pool > Edit Identity Pool > Identity pool ID, only used as ref in resources below
  appSync:
    name: apiName  # defaults to api
    apiId:  # only required for update-appsync    
    authenticationType: AWS_IAM
    ### mappingTemplates / datasources/ functions etc ommitted for brevity:

resources:
  Resources:
    ###Any other resources you might have here
    IAMAuthServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "IAM-Auth-ServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Federated: "cognito-identity.amazonaws.com"
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition: 
                StringEquals: 
                  cognito-identity.amazonaws.com:aud: "${self:custom.cognitoIdentityPoolId}"
        Policies:
          -
            PolicyName: "IAM-Auth-ServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "appsync:GraphQL"
                  Resource:
                    - "arn:aws:appsync:us-west-2:${self:custom.accountId}:apis/${self:custom.appSync.apiId}/*"
                -
                  Effect: "Allow"
                  Action: 
                    - "cognito-identity:GetId"
                  Resource: 
                    - "arn:aws:cognito-identity:*:*:identityPool/${self:custom.cognitoIdentityPoolId}"
```
These resources will only be created if you run `serverless deploy` (not `deploy-appsync`).
At **cognito > Federated Identities > your_identity_pool > Edit identity pool (upper right)** you can set the roles for this identity pool to (in the case of my yml above) IAM-Auth-ServiceRole.  I tested this out and it works.

I think it is OK to close this issue as issue #71 covers any further enhancements. @sid88in, any thoughts?

**Comment by ajmath** [comment]
Okay to close this?

**Comment by yalamber** [comment]
When using AWS_IAM as auth how do I give access to lambda functions to those roles?

**Comment by builtbyproxy** [comment]
Just a quick bump on this issue. If it's good to be closed could we also update the docs? 

The Readme says: 
```
The AWS_IAM authenticationType is not currently supported.
```

**Comment by lhatfield** [comment]
2021 bump, docs still read

`The AWS_IAM authenticationType is not currently supported.`

**Comment by bboure** [comment]
Ups. Thanks @lhatfield 
I will update the doc and close this.

**Comment by bboure** [comment]
After looking at it, I just realized that 
`The AWS_IAM authenticationType is not currently supported.`
actually references the [Playgroud](https://github.com/sid88in/serverless-appsync-plugin#serverless-graphql-playground) feature. IAM is not supported **in the playground**.

Sorry if this was confusion. I'll see if we can improve the doc somehow.
