### ISSUE TITLE
Serverless plugin "serverless-appsync-plugin" initialization errored: Unexpected token )

### ISSUE THREAD

**Issue by lampidudelj** [sid88in/serverless-appsync-plugin#72]
When I'm trying to deploy from example I'm getting this error:
![error](https://user-images.githubusercontent.com/4799937/38421254-6f851e58-399e-11e8-8901-411ad0988c08.jpg)

**Comment by sid88in** [comment]
@lampidudelj I haven't tested this on windows. Can you please check the node versions are latest + latest serverless packages are installed + 0.7 v of serverless plugin? If all that is good then you might want to try out mac/unix to see if this problem is specific to windows. I suspect some version is missing/not compatible.

**Comment by lampidudelj** [comment]
That was it. My node version was  behind. Once updated, everything ran smoothly. Thanks for rapid response!
